language: groovy
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  email: true
sudo: required
before_script:
- sudo apt-get update
- sudo apt-get install lib32z1 lib32ncurses5
before_install:
- chmod +x gradlew
script:
- "./gradlew zipDist"
deploy:
  provider: releases
  file: EtcdSprite/build/distributions/EtcdSprite.zip
  api_key:
      secure: JNMnoT5T4V8z+RjeM15YCuPthT+oFZDMENTmCY+DL+eTiIhoUfXzojVZ7WuKXPoaYMQHxYFqft2zxnDQovPhxdBIkGQfBDVo5ayQ5mRiTqrrXl7rE3wsXpaML7Q1rLxKy2gXaD571C2bcaVtUV8zYPbiiNQIOTXQVT/V3mAS1rzMkOZNTzvi0mckzDuXmq+Kg/CT8w1F8Ybs64zc/zxS0a4vsbbI3AzS9uCMO/zWJbB3wUD0iIg1NOESMt3AkK0E1bWrnDAHbTPxz37C1sl2ySA8aSuwLaEaUmFo+X18m6hqR1gkDNT5+m6jrjZWwfdK/t0OwNyU1/YWwrIwDKHgX/QU8poU6hXUU8A7O8BbbiV4baz7Jdq2x0gO6K0ZdFqeOhdbtUQ6PFBnhw8UA4hSBkOK1kiuGJu8dYkARHObVPKdyk0PrfRAlfiOHCJ764XLPanhnIwYLe0YBv2eXsppcbpIk7zEhYQ0CnmGuECgvb7ImOP/bvdbdmEZmxA7PNDBE0+hfLlf9WdTcJSrLuaPP48eieJif2iwl1H02XRriFY3Jdk5FXk2X2LHq+1REvtirmOnmnK4KjMj2aiJnLiXlJxDAo0juerD54fEQqsZqkpr/a7y7MJ4I8U9M3MZROResyp71Qv/YGdZAUqu6JhbX1zaZKeH5StBQL+G2RHJ748=
