language: groovy # 声明构建语言环境

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:      # 每次构建的时候是否通知
  email: true

sudo: false         # 开启基于容器的Travis CI任务，让编译效率更高。

before_install:
 - chmod +x gradlew  # 改变gradlew的访问权限

script:              # 执行:下面的命令
  - ./gradlew zipDist

#before_deploy:       # 部署之前
  # 使用 mv 命令进行修改apk文件的名字
#  - mv app/build/outputs/apk/app-release.apk app/build/outputs/apk/buff.apk

deploy:              # 部署
  provider: releases # 部署到GitHub Release
  file: EtcdSprite/build/distributions/EtcdSprite.zip # 部署文件路径
#  skip_cleanup: true     # 设置为true以跳过清理,不然apk文件就会被清理
#  on:     # 发布时机
#    tags: true       # tags设置为true表示只有在有tag的情况下才部署