-- 创建SSH信息的表
DROP TABLE IF EXISTS SSH_INFO;
CREATE TABLE SSH_INFO (
  ID                 NUMBER,
  HOST               VARCHAR2,
  NAME               VARCHAR2,
  PASSWORD           VARCHAR2,
  ENTRY_TUNNEL_PORT  NUMBER,
  EXPORT_TUNNEL_HOST VARCHAR2,
  EXPORT_TUNNEL_PORT NUMBER
);
INSERT INTO SSH_INFO
(ID, HOST, NAME, PASSWORD, ENTRY_TUNNEL_PORT, EXPORT_TUNNEL_HOST, EXPORT_TUNNEL_PORT)
VALUES
  (1, '10.10.10.10', 'root', 'password', 8080, '1.1.1.1', 8080);