-- 创建SSH的Session信息的表
DROP TABLE IF EXISTS SESSION_INFO;
CREATE TABLE SESSION_INFO (
  ID                 NUMBER,
  HOST               VARCHAR2,
  PORT               NUMBER,
  NAME               VARCHAR2,
  PASSWORD           VARCHAR2
);
INSERT INTO SESSION_INFO
(ID, HOST, PORT, NAME, PASSWORD)
VALUES
(1, '127.0.0.1', 2202, 'lc', 'ziyu');
  

-- 创建隧道信息
DROP TABLE IF EXISTS TUNNEL_INFO;
CREATE TABLE TUNNEL_INFO (
  ID                 NUMBER,
  ALIAS				 VARCHAR2,
  LOCAL_TUNNEL_HOST  VARCHAR2,
  LOCAL_TUNNEL_PORT  NUMBER,
  IS_LOCAL           BOOLEAN,
  REMOTE_TUNNEL_HOST VARCHAR2,
  REMOTE_TUNNEL_PORT NUMBER,
  SESSION_INFO_ID    NUMBER
);

-- 正向隧道 本端(localhost:80) -> 远端(localhost:80)
INSERT INTO TUNNEL_INFO
(ID,ALIAS,LOCAL_TUNNEL_HOST,LOCAL_TUNNEL_PORT,IS_LOCAL,REMOTE_TUNNEL_HOST,REMOTE_TUNNEL_PORT,SESSION_INFO_ID)
VALUES
(1, 'forwardTunnel', 'localhost', 80, 1, 'localhost', 80, 1);

-- 反向隧道 本端(localhost:80) <- 远端(localhost:8080)
INSERT INTO TUNNEL_INFO
(ID,ALIAS,LOCAL_TUNNEL_HOST,LOCAL_TUNNEL_PORT,IS_LOCAL,REMOTE_TUNNEL_HOST,REMOTE_TUNNEL_PORT,SESSION_INFO_ID)
VALUES
(2, 'reverseTunnel', 'localhost', 80, 0, 'localhost', 8080, 1);