-- 创建SSH的Session信息的表
DROP TABLE IF EXISTS SESSION_INFO;
CREATE TABLE SESSION_INFO (
  ID                 NUMBER,
  HOST               VARCHAR2,
  NAME               VARCHAR2,
  PASSWORD           VARCHAR2,
  ENTRY_TUNNEL_PORT  NUMBER,
  EXPORT_TUNNEL_HOST VARCHAR2,
  EXPORT_TUNNEL_PORT NUMBER
);
INSERT INTO SESSION_INFO
(ID, HOST, NAME, PASSWORD, ENTRY_TUNNEL_PORT, EXPORT_TUNNEL_HOST, EXPORT_TUNNEL_PORT)
VALUES
(1, '10.10.10.10', 'root', 'password', 8080, '1.1.1.1', 8080);
  

-- 创建隧道信息
DROP TABLE IF EXISTS TUNNEL_INFO;
CREATE TABLE TUNNEL_INFO (
  ID                 NUMBER,
  ALIAS				 VARCHAR2,
  LOCAL_TUNNEL_HOST  VARCHAR2,
  LOCAL_TUNNEL_PORT  VARCHAR2,
  IS_LOCAL           BOOLEAN,
  REMOTE_TUNNEL_HOST NUMBER,
  REMOTE_TUNNEL_PORT VARCHAR2,
  SESSION_INFO_ID    NUMBER
);

INSERT INTO TUNNEL_INFO
(ID,ALIAS,LOCAL_TUNNEL_HOST,LOCAL_TUNNEL_PORT,IS_LOCAL,REMOTE_TUNNEL_HOST,REMOTE_TUNNEL_PORT,SESSION_INFO_ID)
VALUES
(1, 'forwardTunnel', 'localhost', '80', 0, 'localhost', '80', 1);